#!/usr/bin/env python3
"""Transcribe the 256px Prosperity treasure-chest master into a native .glyph grid.

`art/hud-icon-256.png` is a finished 256×256 pixel-art open treasure chest
overflowing with gold coins and a diamond-cyan gem (27 colors) — its own
high-detail artwork, not an upscale of the 32px HUD master. Because it is clean
indexed pixel art, this script reads it pixel-by-pixel and emits the *exact*
ASCII-grid .glyph — each distinct opaque color becomes a legend token, fully
transparent pixels become '.'. glyph.py rasterizes it back pixel-identical to the
master, so the committed `chest-256.glyph` is a re-renderable source for it (ASSETS.md).

Requires ImageMagick (`convert`), already used across the suite's art tooling.

Run:  python3 art/glyphs/chest-256.gen.py
      python3 .ai/skills/mc-textures/scripts/glyph.py art/glyphs/chest-256.glyph -o out.png
"""
import re
import subprocess

MASTER = "art/hud-icon-256.png"
OUT = "art/glyphs/chest-256.glyph"

dump = subprocess.run(
    ["convert", MASTER, "-depth", "8", "txt:-"],
    check=True, capture_output=True, text=True).stdout

hdr = re.search(r"enumeration:\s*(\d+),(\d+)", dump)
W, H = int(hdr.group(1)), int(hdr.group(2))
assert W == H, f"expected a square master, got {W}x{H}"

px = re.compile(r"^(\d+),(\d+):\s*\((\d+),(\d+),(\d+),(\d+)\)")
grid = [[None] * W for _ in range(H)]
for line in dump.splitlines():
    m = px.match(line)
    if not m:
        continue
    x, y, r, g, b, a = (int(v) for v in m.groups())
    if a == 0:
        continue  # fully transparent -> '.'
    grid[y][x] = "#%02X%02X%02X" % (r, g, b) if a == 255 else "#%02X%02X%02X%02X" % (r, g, b, a)

pool = "@$%&*+=oOxX0123456789abcdefghijklmnpqrstuvwzABCDEFGHIJKLMNPQRSTUVWZ?!~^"
used = []
for row in grid:
    for c in row:
        if c and c not in used:
            used.append(c)
assert len(used) <= len(pool), f"too many colors: {len(used)}"
key2ch = {k: pool[i] for i, k in enumerate(used)}

lines = [f"# Prosperity 256px treasure chest — generated by chest-256.gen.py.",
         f"# Exact transcription of the {W}px master {MASTER}: an open treasure chest",
         f"# overflowing with gold coins and a diamond-cyan gem. Re-run to refresh from the master.",
         f"size: {W}", "", "legend:", "  . transparent"]
for k in used:
    lines.append(f"  {key2ch[k]} {k}")
lines.append("")
lines.append("frame:")
for row in grid:
    lines.append("  " + "".join(key2ch[c] if c else "." for c in row))

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {OUT}  ({len(used)} colors, {W}x{H} from {MASTER})")
