#!/usr/bin/env python3
"""Transcribe Prosperity's HUD loot-tier chest master into a 32px .glyph grid.

The brand master `art/hud-icon-16.png` is already a finished 32×32 pixel-art open
treasure chest (27 colors; the 256px master is its nearest-neighbor upscale), and
32px is exactly what the HUD ships (HUD-STANDARD blits it to ~16px). So rather than
hand-approximate it, this script reads the master pixel-by-pixel and emits the
*exact* ASCII-grid .glyph — each distinct opaque color becomes a legend token,
fully transparent pixels become '.'. glyph.py then rasterizes it back to a texture
that is pixel-identical to the master, and the committed .glyph is a re-renderable
source for it (ASSETS.md).

Requires ImageMagick (`convert`), already used across the suite's art tooling.

Run:  python3 art/glyphs/hud_icon.gen.py
      python3 .ai/skills/mc-textures/scripts/glyph.py art/glyphs/hud_icon.glyph \
              -o src/main/resources/assets/prosperity/textures/gui/hud_icon.png
"""
import re
import subprocess

MASTER = "art/hud-icon-16.png"
OUT = "art/glyphs/hud_icon.glyph"

# Dump every pixel as 8-bit RGBA via ImageMagick's text enumeration.
dump = subprocess.run(
    ["convert", MASTER, "-depth", "8", "txt:-"],
    check=True, capture_output=True, text=True).stdout

# Header line: "# ImageMagick pixel enumeration: W,H,..."
hdr = re.search(r"enumeration:\s*(\d+),(\d+)", dump)
W, H = int(hdr.group(1)), int(hdr.group(2))
assert W == H == 32, f"expected a 32x32 master, got {W}x{H}"

px = re.compile(r"^(\d+),(\d+):\s*\((\d+),(\d+),(\d+),(\d+)\)")
grid = [[None] * W for _ in range(H)]
for line in dump.splitlines():
    m = px.match(line)
    if not m:
        continue
    x, y, r, g, b, a = (int(v) for v in m.groups())
    if a == 0:
        continue  # fully transparent -> '.'
    grid[y][x] = "#%02X%02X%02X" % (r, g, b) if a == 255 else "#%02X%02X%02X%02X" % (r, g, b, a)

# Assign a legend token to each distinct color, in first-appearance order.
pool = "@$%&*+=oOxX0123456789abcdefghijklmnpqrstuvwzABCDEFGHIJKLMNPQRSTUVWZ?!~^"
used = []
for row in grid:
    for c in row:
        if c and c not in used:
            used.append(c)
assert len(used) <= len(pool), f"too many colors: {len(used)}"
key2ch = {k: pool[i] for i, k in enumerate(used)}

lines = [f"# Prosperity HUD loot-tier chest — generated by hud_icon.gen.py.",
         f"# Exact transcription of the {W}px master {MASTER} (slot 3 in the Concord",
         f"# HUD stack; blitted to ~16px). Re-run the generator to refresh from the master.",
         f"size: {W}", "", "legend:", "  . transparent"]
for k in used:
    lines.append(f"  {key2ch[k]} {k}")
lines.append("")
lines.append("frame:")
for row in grid:
    lines.append("  " + "".join(key2ch[c] if c else "." for c in row))

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {OUT}  ({len(used)} colors, {W}x{H} from {MASTER})")
